### ISSUE TITLE
 [ERR]  Missing tornado.raw in pwd?

### ISSUE THREAD

**Issue by pixelBaron117** [samogod/tornado#10]
Hello, geting this error : 
[14-05-2024 11:13:20] [ERR]  Failed to read tornado.raw.
[14-05-2024 11:13:20] [ERR]  Missing tornado.raw in pwd?

![image](https://github.com/samogod/tornado/assets/138985926/88837a06-1d7d-42a6-995f-ee45cb8068a3)

**Comment by ahdplayer** [comment]
this happens when tornado fails to create a hidden service. msfvenom crashes and doesnt create tornado.raw because the the program didnt give it a valid address. this should be fixed now. i will still make a pull request to crash the program if onion hostname doesnt exists to prevent something like this in the future.

dont create an empty tornado.raw file, it wont do anything.
